# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bolsa B3
email: pulgovisk@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre a Bolsa de Valores
  
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bolsab3.github.io" # the base hostname & protocol for your site

copyright:
   name: João Paulo Pulga
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Comments
disqus: yes
disqus-shortname: BolsaB3

#social
github: https://github.com/bolsab3/bolsab3.github.io
email: pulgovisk@protonmail.com

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

